In [1]:
import cv2
import numpy as np
import datetime
np.set_printoptions(precision=10)

In [2]:
pts_gps_old = np.array([[23.90377194, 121.53645972], 
                      [23.90391278, 121.53635972], 
                      [23.90377861, 121.53629389],
                      [23.90375806, 121.53625750],
                      [23.90362417, 121.53638333],
                      [23.90367667, 121.53651000],
                      ], dtype=np.float32)
pts_gps = (pts_gps_old - np.float32([23.903, 121.535])) * 5000000
print pts_gps
pts_xys = np.array([[830, 413],
                      [63, 421],
                      [461, 588],
                      [489, 755],
                      [1618, 555],
                      [1252, 406],
                      ], dtype=np.float32)

[[3862.3809814453 7286.0717773438]
 [4568.0999755859 6790.1611328125]
 [3890.9912109375 6446.8383789062]
 [3795.6237792969 6256.103515625 ]
 [3118.5150146484 6904.6020507812]
 [3385.5438232422 7514.9536132812]]


In [3]:
# input four pairs of the corresponding points, find out perspective transformation matrix M

In [4]:
pts1 = np.array([pts_gps[0], pts_gps[1], pts_gps[2], pts_gps[3], pts_gps[4], pts_gps[5]], dtype=np.float32)
pts2 = np.array([pts_xys[0], pts_xys[1], pts_xys[2], pts_xys[3], pts_xys[4], pts_xys[5]], dtype=np.float32)

In [5]:
M, mask = cv2.findHomography(pts1, pts2)
print M

[[ 1.5847379094e-01 -1.7338530126e-01  4.4021798238e+02]
 [-3.9653143915e-04 -3.1891142167e-02  1.3204447855e+02]
 [-4.1088480069e-05 -1.4970626904e-04  1.0000000000e+00]]


In [6]:
def compute_gps2xy(idx):
    print("input %.10f, %.10f " % (pts_gps[idx, 0], pts_gps[idx, 1]))
    expect_result = np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    print("input gps: ", np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T)
    result_pre = np.matrix(M) * np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_xy: ", result)
    diff = result - expect_result
    print("diff_xy: ", diff)

In [7]:
#驗證 gps -> xy for point 0
#compute_gps2xy(0)

In [8]:
#驗證 gps -> xy for point 1
#compute_gps2xy(1)

In [9]:
#驗證 gps -> xy for point 2
#compute_gps2xy(2)

In [10]:
#驗證 gps -> xy for point 3
#compute_gps2xy(3)

In [11]:
#驗證 gps -> xy for point 4
#compute_gps2xy(4)

In [12]:
#驗證 gps -> xy for point 5
#compute_gps2xy(5)

In [13]:
# inverse Transform
inv_M = np.linalg.inv(M) 
print inv_M


[[ 7.5771366285e+00 -6.7177094839e+01  5.5347726597e+03]
 [ 3.1431518529e+00 -1.1035252990e+02  1.3187770300e+04]
 [ 7.8188256427e-04 -1.9280670253e-02  3.2017072847e+00]]


In [14]:
def compute_xy2gps(idx):
    expect_result = np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    print("input xy: ", np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T)
    result_pre = np.matrix(inv_M) * np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_gps: ", result)
    diff = result - expect_result
    print("diff_gps: ", diff)

In [15]:
#驗證 xy -> gps for point 0
compute_xy2gps(0)

('input xy: ', matrix([[830.],
        [413.],
        [  1.]]))
('output_gps: ', matrix([[3.8714464627e+03],
        [7.2415417898e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[  9.0654812129],
        [-44.5299875504],
        [  0.          ]]))


In [16]:
#驗證 xy -> gps for point 1
compute_xy2gps(1)

('input xy: ', matrix([[ 63.],
        [421.],
        [  1.]]))
('output_gps: ', matrix([[4.5763514934e+03],
        [6.7964020045e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[8.2515178083],
        [6.2408716584],
        [0.          ]]))


In [17]:
#驗證 xy -> gps for point 2
compute_xy2gps(2)

('input xy: ', matrix([[461.],
        [588.],
        [  1.]]))
('output_gps: ', matrix([[3.9193277824e+03],
        [6.4631905555e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[28.3365714304],
        [16.3521766275],
        [ 0.          ]]))


In [18]:
#驗證 xy -> gps for point 3
compute_xy2gps(3)

('input xy: ', matrix([[489.],
        [755.],
        [  1.]]))
('output_gps: ', matrix([[3.7801194040e+03],
        [6.2510047408e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[-15.5043752972],
        [ -5.098774783 ],
        [  0.          ]]))


In [19]:
#驗證 xy -> gps for point 4
compute_xy2gps(4)

('input xy: ', matrix([[1.618e+03],
        [5.550e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[3.1262070015e+03],
        [6.8932324041e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[  7.6919868146],
        [-11.3696466721],
        [  0.          ]]))


In [20]:
#驗證 xy -> gps for point 5
compute_xy2gps(5)

('input xy: ', matrix([[1.252e+03],
        [4.060e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[3.3593231075e+03],
        [7.5891534090e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[-26.2207157098],
        [ 74.1997956955],
        [  0.          ]]))


In [21]:
img = cv2.imread('1009.jpg', cv2.IMREAD_COLOR)
imgReg = cv2.warpPerspective(img, inv_M, (10000, 10000))
cv2.imwrite("1009_reg.jpg", imgReg)

True