In [1]:
import cv2
import numpy as np
import datetime

In [2]:
# 以下利用3＋3個點, 找到Affine transformation matrix M

In [3]:
pts1 = np.float32([[23.90367667, 121.53651000], [23.90391278, 121.53635972], [23.90375806, 121.53625750]], dtype='float128')
pts2 = np.float32([[1252, 406], [63, 421], [489, 755]], dtype='float128')

In [4]:
now = datetime.datetime.now()
M = cv2.getAffineTransform(pts1, pts2)
diff = datetime.datetime.now() - now   #測量 cv2.getAffineTransform() 消耗時間
print M
print diff

[[-3.96057561e+06  1.74035601e+06 -1.16843217e+08]
 [-9.82299593e+05 -1.70617723e+06  2.30843799e+08]]
0:00:00.000181


In [5]:
# 取得 invertAffineTransform
now = datetime.datetime.now()
inv_M = cv2.invertAffineTransform(M)
diff = datetime.datetime.now() - now   #測量 cv2.invertAffineTransform() 消耗時間
print inv_M
print diff

[[-2.01509183e-07 -2.05545890e-07  2.39040127e+01]
 [ 1.16015139e-07 -4.67766385e-07  1.21536551e+02]]
0:00:00.000126


In [6]:
# 驗證特徵點1
M2 = np.array([1252, 406, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90367667, 121.53651000]).reshape(2,1)
print diff

[[ 3.16694340e-07]
 [-3.34716798e-06]]


In [7]:
M2.dtype

dtype('float64')

In [8]:
result.dtype

dtype('float64')

In [9]:
# 驗證特徵點2
M2 = np.array([63, 421, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90391278, 121.53635972]).reshape(2,1)
print diff

[[7.17924809e-07]
 [1.97433594e-06]]


In [10]:
# 驗證特徵點3
M2 = np.array([489, 755, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90375806, 121.53625750]).reshape(2,1)
print diff

[[ 9.42685549e-07]
 [-2.61718750e-06]]


In [11]:
# 驗證測試點1
M2 = np.array([830, 413, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90377194, 121.53645972]).reshape(2,1)
print diff

[[-1.13552516e-05]
 [-5.29992134e-06]]


In [12]:
# 驗證測試點2
M2 = np.array([461, 588, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90377861, 121.53629389]).reshape(2,1)
print diff

[[2.03611063e-05]
 [3.58613749e-05]]


In [13]:
# 驗證測試點3
M2 = np.array([1618, 555, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90362417, 121.53638333]).reshape(2,1)
print diff

[[-5.15620043e-05]
 [ 9.60871815e-05]]
