In [1]:
import cv2
import numpy as np
import datetime
np.set_printoptions(precision=10)

In [2]:
pts_gps = np.array([[23.90377194, 121.53645972], 
                      [23.90391278, 121.53635972], 
                      [23.90377861, 121.53629389],
                      [23.90375806, 121.53625750],
                      [23.90362417, 121.53638333],
                      [23.90367667, 121.53651000],
                      ], dtype=np.float128)
pts_xys = np.array([[830, 413],
                      [63, 421],
                      [461, 588],
                      [489, 755],
                      [1618, 555],
                      [1252, 406],
                      ], dtype=np.float128)

In [3]:
# input four pairs of the corresponding points, find out perspective transformation matrix M

In [4]:
pts1 = np.array([pts_gps[0], pts_gps[1], pts_gps[2], pts_gps[3], pts_gps[4], pts_gps[5]], dtype=np.float64)
pts2 = np.array([pts_xys[0], pts_xys[1], pts_xys[2], pts_xys[3], pts_xys[4], pts_xys[5]], dtype=np.float64)

In [5]:
M, mask = cv2.findHomography(pts1, pts2)
print M

[[ 8.1789041009e+00 -9.0193727963e+00  9.0067378277e+02]
 [-1.1599166129e-01 -1.6191222254e+00  1.9955395520e+02]
 [-2.3067101235e-03 -7.7743216810e-03  1.0000000000e+00]]


In [6]:
def compute_gps2xy(idx):
    print("input %.10f, %.10f " % (pts_gps[idx, 0], pts_gps[idx, 1]))
    expect_result = np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    print("input gps: ", np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T)
    result_pre = np.matrix(M) * np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_xy: ", result)
    diff = result - expect_result
    print("diff_xy: ", diff)

In [7]:
#驗證 gps -> xy for point 0
#compute_gps2xy(0)

In [8]:
#驗證 gps -> xy for point 1
#compute_gps2xy(1)

In [9]:
#驗證 gps -> xy for point 2
#compute_gps2xy(2)

In [10]:
#驗證 gps -> xy for point 3
#compute_gps2xy(3)

In [11]:
#驗證 gps -> xy for point 4
#compute_gps2xy(4)

In [12]:
#驗證 gps -> xy for point 5
#compute_gps2xy(5)

In [13]:
# inverse Transform
inv_M = np.linalg.inv(M) 
print inv_M


[[ 1.4563930478e+03 -4.3379495535e+04  7.3448148733e+06]
 [ 7.4044010365e+03 -2.2055906304e+05  3.7344483494e+07]
 [ 6.0923672100e+01 -1.8147610272e+03  3.0727138652e+05]]


In [14]:
def compute_xy2gps(idx):
    expect_result = np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    print("input xy: ", np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T)
    result_pre = np.matrix(inv_M) * np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_gps: ", result)
    diff = result - expect_result
    print("diff_gps: ", diff)

In [15]:
#驗證 xy -> gps for point 0
compute_xy2gps(0)

('input xy: ', matrix([[830.],
        [413.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.9037734505],
        [121.5364524139],
        [  1.          ]], dtype=float128))
('diff_gps: ', matrix([[ 1.5104691573e-06],
        [-7.3061236750e-06],
        [ 0.0000000000e+00]], dtype=float128))


In [16]:
#驗證 xy -> gps for point 1
compute_xy2gps(1)

('input xy: ', matrix([[ 63.],
        [421.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.9039189608],
        [121.5363648272],
        [  1.          ]], dtype=float128))
('diff_gps: ', matrix([[6.1808420271e-06],
        [5.1071976262e-06],
        [0.0000000000e+00]], dtype=float128))


In [17]:
#驗證 xy -> gps for point 2
compute_xy2gps(2)

('input xy: ', matrix([[461.],
        [588.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.9037838173],
        [121.5362967063],
        [  1.          ]], dtype=float128))
('diff_gps: ', matrix([[5.2072931422e-06],
        [2.8163016004e-06],
        [0.0000000000e+00]], dtype=float128))


In [18]:
#驗證 xy -> gps for point 3
compute_xy2gps(3)

('input xy: ', matrix([[489.],
        [755.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.9037556436],
        [121.5362537865],
        [  1.          ]], dtype=float128))
('diff_gps: ', matrix([[-2.4164426969e-06],
        [-3.7134867348e-06],
        [ 0.0000000000e+00]], dtype=float128))


In [19]:
#驗證 xy -> gps for point 4
compute_xy2gps(4)

('input xy: ', matrix([[1.618e+03],
        [5.550e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.9036256547],
        [121.5363817467],
        [  1.          ]], dtype=float128))
('diff_gps: ', matrix([[ 1.4846622668e-06],
        [-1.5832960287e-06],
        [ 0.0000000000e+00]], dtype=float128))


In [20]:
#驗證 xy -> gps for point 5
compute_xy2gps(5)

('input xy: ', matrix([[1.252e+03],
        [4.060e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.9036718412],
        [121.5365182758],
        [  1.          ]], dtype=float128))
('diff_gps: ', matrix([[-4.8288309465e-06],
        [ 8.2758474950e-06],
        [ 0.0000000000e+00]], dtype=float128))
