In [1]:
import cv2
import numpy as np
import datetime

In [2]:
# input 3 gps + 3 xy points, find out Affine transformation matrix M

In [3]:
pts1 = np.float32([[23.90344056, 121.53592722], [23.90368083, 121.53650361], [23.90387389, 121.53634472]])
pts2 = np.float32([[876, 364], [51, 788], [1911, 745]])

In [4]:
now = datetime.datetime.now()
M = cv2.getAffineTransform(pts1, pts2)
diff = datetime.datetime.now() - now   #measure cv2.getAffineTransform() computing time
print M
print diff

[[ 6.30014165e+06 -4.03406397e+06  3.39689519e+08]
 [ 2.86270797e+05  6.12592078e+05 -8.12944389e+07]]
0:00:00.012999


In [5]:
# get invertAffineTransform
now = datetime.datetime.now()
inv_M = cv2.invertAffineTransform(M)
diff = datetime.datetime.now() - now   #measure cv2.invertAffineTransform() computing time
print inv_M
print diff

[[ 1.22170192e-07  8.04519661e-07  2.39030406e+01]
 [-5.70914309e-08  1.25644706e-06  1.21535519e+02]]
0:00:00.000541


In [6]:
# compute feature point 1 from xy to gps and see the difference
M2 = np.array([876, 364, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90344056, 121.53592722]).reshape(2,1)
print diff

[[-8.45361434e-08]
 [-4.01152363e-07]]


In [7]:
# compute feature point 2 from xy to gps and see the difference
M2 = np.array([51, 788, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90368083, 121.53650361]).reshape(2,1)
print diff

[[-2.86084081e-08]
 [ 3.04283202e-06]]


In [8]:
# compute feature point 3 from xy to gps and see the difference
M2 = np.array([1911, 745, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90387389, 121.53634472]).reshape(2,1)
print diff

[[-4.46396491e-07]
 [ 1.71554686e-06]]


In [9]:
# compute feature point 4 from xy to gps and see the difference
M2 = np.array([1066, 376, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90353583, 121.53588083]).reshape(2,1)
print diff

[[-6.24879637e-05]
 [ 5.02188405e-05]]


In [10]:
# compute feature point 5 from xy to gps and see the difference
M2 = np.array([148, 396, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90325667, 121.53627833]).reshape(2,1)
print diff

[[ 0.00012061]
 [-0.00026974]]


In [11]:
# compute feature point 6 from xy to gps and see the difference
M2 = np.array([910, 958, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90377194, 121.53645972]).reshape(2,1)
print diff

[[0.00015057]
 [0.00021149]]


In [12]:
# compute feature point 7 from xy to gps and see the difference
M2 = np.array([678, 454, 1.0])
M2 = M2.reshape(3, 1)
result = np.matmul(inv_M, M2)
# p = inv_M * p'  
diff = result - np.array([23.90356778, 121.53624333]).reshape(2,1)
print diff

[[-7.90874647e-05]
 [-1.92126814e-04]]
