In [1]:
import cv2
import numpy as np
import datetime
np.set_printoptions(precision=10)

In [2]:
pts_gps = np.array([[23.90344056, 121.53592722], 
                      [23.90368083, 121.53650361], 
                      [23.90387389, 121.53634472],
                      [23.90353583, 121.53588083],
                      [23.90325667, 121.53627833],
                      [23.90377194, 121.53645972],
                      [23.90356778, 121.53624333],
                      [23.90360417, 121.53637861],
                      [23.90355778, 121.53626361],
                      [23.90367083, 121.53619194],
                      [23.90379306, 121.53615306],
                      [23.90376639, 121.53642389],
                      [23.90339194, 121.53638639]], dtype=np.float32)
pts_xys = np.array([[876, 364],
                      [51, 788],
                      [1911, 745],
                      [1066, 376],
                      [148, 396],
                      [910, 958],
                      [678, 454],
                      [417, 540],
                      [615, 456],
                      [1077, 475],
                      [1554, 503],
                      [1036, 809],
                      [55, 448]], dtype=np.float32)

In [3]:
# input four pairs of the corresponding points, find out perspective transformation matrix M

In [4]:
pts1 = np.array([pts_gps[0], pts_gps[1], pts_gps[2], pts_gps[3]], dtype=np.float32)
pts2 = np.array([pts_xys[0], pts_xys[1], pts_xys[2], pts_xys[3]], dtype=np.float32)

In [5]:
M = cv2.getPerspectiveTransform(pts1, pts2)
print M

[[ 6.4763128068e+00 -1.2361256119e+01  1.3475362343e+03]
 [-3.0607883870e-01 -2.2382773441e+00  2.7934979004e+02]
 [-3.7027438306e-03 -7.4997184563e-03  1.0000000000e+00]]


In [6]:
def compute_gps2xy(idx):
    print("input %.10f, %.10f " % (pts_gps[idx, 0], pts_gps[idx, 1]))
    expect_result = np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    print("input gps: ", np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T)
    result_pre = np.matrix(M) * np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_xy: ", result)
    diff = result - expect_result
    print("diff_xy: ", diff)

In [7]:
#驗證 gps -> xy for point 0
compute_gps2xy(0)

input 23.9034404755, 121.5359268188 
('input gps: ', matrix([[ 23.9034404755],
        [121.5359268188],
        [  1.          ]]))
('output_xy: ', matrix([[879.5367380683],
        [362.9946064416],
        [  1.          ]]))
('diff_xy: ', matrix([[ 3.5367380683],
        [-1.0053935584],
        [ 0.          ]]))


In [8]:
#驗證 gps -> xy for point 1
compute_gps2xy(1)

input 23.9036808014, 121.5365066528 
('input gps: ', matrix([[ 23.9036808014],
        [121.5365066528],
        [  1.          ]]))
('output_xy: ', matrix([[ 50.9959498886],
        [800.6493319306],
        [  1.          ]]))
('diff_xy: ', matrix([[-4.0501114010e-03],
        [ 1.2649331931e+01],
        [ 0.0000000000e+00]]))


In [9]:
#驗證 gps -> xy for point 2
compute_gps2xy(2)

input 23.9038734436, 121.5363464355 
('input gps: ', matrix([[ 23.9038734436],
        [121.5363464355],
        [  1.          ]]))
('output_xy: ', matrix([[1.9356641598e+03],
        [7.4693468900e+02],
        [1.0000000000e+00]]))
('diff_xy: ', matrix([[24.6641598208],
        [ 1.9346889996],
        [ 0.          ]]))


In [10]:
#驗證 gps -> xy for point 3
compute_gps2xy(3)

input 23.9035358429, 121.5358810425 
('input gps: ', matrix([[ 23.9035358429],
        [121.5358810425],
        [  1.          ]]))
('output_xy: ', matrix([[1.0646480555e+03],
        [3.7492504279e+02],
        [1.0000000000e+00]]))
('diff_xy: ', matrix([[-1.3519445187],
        [-1.0749572068],
        [ 0.          ]]))


In [11]:
#驗證 gps -> xy for point 4
compute_gps2xy(4)

input 23.9032573700, 121.5362777710 
('input gps: ', matrix([[ 23.90325737 ],
        [121.536277771],
        [  1.         ]]))
('output_xy: ', matrix([[ 33.0903937311],
        [358.5072329339],
        [  1.          ]]))
('diff_xy: ', matrix([[-114.9096062689],
        [ -37.4927670661],
        [   0.          ]]))


In [12]:
#驗證 gps -> xy for point 5
compute_gps2xy(5)

input 23.9037723541, 121.5364608765 
('input gps: ', matrix([[ 23.9037723541],
        [121.5364608765],
        [  1.          ]]))
('output_xy: ', matrix([[1.0040375948e+03],
        [8.5904169402e+02],
        [1.0000000000e+00]]))
('diff_xy: ', matrix([[ 94.0375948063],
        [-98.9583059794],
        [  0.          ]]))


In [13]:
#驗證 gps -> xy for point 6
compute_gps2xy(6)

input 23.9035682678, 121.5362396240 
('input gps: ', matrix([[ 23.9035682678],
        [121.536239624 ],
        [  1.          ]]))
('output_xy: ', matrix([[725.429323897],
        [441.23697351 ],
        [  1.         ]]))
('diff_xy: ', matrix([[ 47.429323897],
        [-12.76302649 ],
        [  0.         ]]))


In [14]:
#驗證 gps -> xy for point 7
compute_gps2xy(7)

input 23.9036045074, 121.5363769531 
('input gps: ', matrix([[ 23.9036045074],
        [121.5363769531],
        [  1.          ]]))
('output_xy: ', matrix([[474.7225710891],
        [520.3673815685],
        [  1.          ]]))
('diff_xy: ', matrix([[ 57.7225710891],
        [-19.6326184315],
        [  0.          ]]))


In [15]:
#驗證 gps -> xy for point 8
compute_gps2xy(8)

input 23.9035587311, 121.5362625122 
('input gps: ', matrix([[ 23.9035587311],
        [121.5362625122],
        [  1.          ]]))
('output_xy: ', matrix([[655.0913800526],
        [444.6277388433],
        [  1.          ]]))
('diff_xy: ', matrix([[ 40.0913800526],
        [-11.3722611567],
        [  0.          ]]))


In [16]:
#驗證 gps -> xy for point 9
compute_gps2xy(9)

input 23.9036712646, 121.5361938477 
('input gps: ', matrix([[ 23.9036712646],
        [121.5361938477],
        [  1.          ]]))
('output_xy: ', matrix([[1.0762912697e+03],
        [4.6565638687e+02],
        [1.0000000000e+00]]))
('diff_xy: ', matrix([[-0.7087302938],
        [-9.3436131328],
        [ 0.          ]]))


In [17]:
#驗證 gps -> xy for point 10
compute_gps2xy(10)

input 23.9037933350, 121.5361557007 
('input gps: ', matrix([[ 23.903793335 ],
        [121.5361557007],
        [  1.          ]]))
('output_xy: ', matrix([[1.4967178154e+03],
        [5.0221483989e+02],
        [1.0000000000e+00]]))
('diff_xy: ', matrix([[-57.2821845557],
        [ -0.7851601149],
        [  0.          ]]))


In [18]:
#驗證 gps -> xy for point 11
compute_gps2xy(11)

input 23.9037666321, 121.5364227295 
('input gps: ', matrix([[ 23.9037666321],
        [121.5364227295],
        [  1.          ]]))
('output_xy: ', matrix([[1.0867518339e+03],
        [7.4292902224e+02],
        [1.0000000000e+00]]))
('diff_xy: ', matrix([[ 50.7518338791],
        [-66.0709777582],
        [  0.          ]]))


In [19]:
#驗證 gps -> xy for point 12
compute_gps2xy(12)

input 23.9033927917, 121.5363845825 
('input gps: ', matrix([[ 23.9033927917],
        [121.5363845825],
        [  1.          ]]))
('output_xy: ', matrix([[-92.2337823183],
        [416.889169168 ],
        [  1.          ]]))
('diff_xy: ', matrix([[-147.2337823183],
        [ -31.110830832 ],
        [   0.          ]]))


In [20]:
# inverse Transform
inv_M = np.linalg.inv(M) 
print inv_M


[[-2.0763083328e+03  3.2690271077e+04 -6.3341196497e+06]
 [-1.0557219926e+04  1.6621032613e+05 -3.2204583322e+07]
 [-8.6864214996e+01  1.3675743500e+03 -2.6497793038e+05]]


In [21]:
def compute_xy2gps(idx):
    expect_result = np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    print("input xy: ", np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T)
    result_pre = np.matrix(inv_M) * np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_gps: ", result)
    diff = result - expect_result
    print("diff_gps: ", diff)

In [22]:
#驗證 xy -> gps for point 0
compute_xy2gps(0)

('input xy: ', matrix([[876.],
        [364.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9034429118],
        [121.5359348465],
        [  1.          ]]))
('diff_gps: ', matrix([[2.4363553024e-06],
        [8.0276872012e-06],
        [0.0000000000e+00]]))


In [23]:
#驗證 xy -> gps for point 1
compute_xy2gps(1)

('input xy: ', matrix([[ 51.],
        [788.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9036775098],
        [121.5365048209],
        [  1.          ]]))
('diff_gps: ', matrix([[-3.2916116481e-06],
        [-1.8319075679e-06],
        [ 0.0000000000e+00]]))


In [24]:
#驗證 xy -> gps for point 2
compute_xy2gps(2)

('input xy: ', matrix([[1.911e+03],
        [7.450e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[ 23.9038701416],
        [121.5363478717],
        [  1.          ]]))
('diff_gps: ', matrix([[-3.3020144379e-06],
        [ 1.4362029646e-06],
        [ 0.0000000000e+00]]))


In [25]:
#驗證 xy -> gps for point 3
compute_xy2gps(3)

('input xy: ', matrix([[1.066e+03],
        [3.760e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[ 23.9035391091],
        [121.5358868454],
        [  1.          ]]))
('diff_gps: ', matrix([[3.2662239917e-06],
        [5.8029243490e-06],
        [0.0000000000e+00]]))


In [26]:
#驗證 xy -> gps for point 4
compute_xy2gps(4)

('input xy: ', matrix([[148.],
        [396.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9033823881],
        [121.5363099063],
        [  1.          ]]))
('diff_gps: ', matrix([[1.2501814623e-04],
        [3.2135322570e-05],
        [0.0000000000e+00]]))


In [27]:
#驗證 xy -> gps for point 5
compute_xy2gps(5)

('input xy: ', matrix([[910.],
        [958.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9037738632],
        [121.5364842077],
        [  1.          ]]))
('diff_gps: ', matrix([[1.5090320780e-06],
        [2.3331241209e-05],
        [0.0000000000e+00]]))


In [28]:
#驗證 xy -> gps for point 6
compute_xy2gps(6)

('input xy: ', matrix([[678.],
        [454.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9035749197],
        [121.5362715048],
        [  1.          ]]))
('diff_gps: ', matrix([[6.6519234174e-06],
        [3.1880767821e-05],
        [0.0000000000e+00]]))


In [29]:
#驗證 xy -> gps for point 7
compute_xy2gps(7)

('input xy: ', matrix([[417.],
        [540.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9036107802],
        [121.5363978203],
        [  1.          ]]))
('diff_gps: ', matrix([[6.2727450398e-06],
        [2.0867136655e-05],
        [0.0000000000e+00]]))


In [30]:
#驗證 xy -> gps for point 8
compute_xy2gps(8)

('input xy: ', matrix([[615.],
        [456.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9035654942],
        [121.5362882309],
        [  1.          ]]))
('diff_gps: ', matrix([[6.7630979643e-06],
        [2.5718711399e-05],
        [0.0000000000e+00]]))


In [31]:
#驗證 xy -> gps for point 9
compute_xy2gps(9)

('input xy: ', matrix([[1.077e+03],
        [4.750e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[ 23.9036785946],
        [121.5362111572],
        [  1.          ]]))
('diff_gps: ', matrix([[7.3299170786e-06],
        [1.7309588685e-05],
        [0.0000000000e+00]]))


In [32]:
#驗證 xy -> gps for point 10
compute_xy2gps(10)

('input xy: ', matrix([[1.554e+03],
        [5.030e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[ 23.9038085912],
        [121.5361419763],
        [  1.          ]]))
('diff_gps: ', matrix([[ 1.5256214034e-05],
        [-1.3724368102e-05],
        [ 0.0000000000e+00]]))


In [33]:
#驗證 xy -> gps for point 11
compute_xy2gps(11)

('input xy: ', matrix([[1.036e+03],
        [8.090e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[ 23.9037698357],
        [121.536446758 ],
        [  1.          ]]))
('diff_gps: ', matrix([[3.2036213398e-06],
        [2.4028479700e-05],
        [0.0000000000e+00]]))


In [34]:
#驗證 xy -> gps for point 12
compute_xy2gps(12)

('input xy: ', matrix([[ 55.],
        [448.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9034652627],
        [121.53638575  ],
        [  1.          ]]))
('diff_gps: ', matrix([[7.2470993079e-05],
        [1.1674587768e-06],
        [0.0000000000e+00]]))
