In [1]:
import cv2
import numpy as np
import datetime
np.set_printoptions(formatter={'float': '{: 0.8f}'.format})

In [2]:
pts_gps = np.array([[23.90344056, 121.53592722], 
                      [23.90368083, 121.53650361], 
                      [23.90387389, 121.53634472],
                      [23.90353583, 121.53588083],
                      [23.90325667, 121.53627833],
                      [23.90377194, 121.53645972],
                      [23.90356778, 121.53624333],
                      [23.90360417, 121.53637861],
                      [23.90355778, 121.53626361],
                      [23.90367083, 121.53619194],
                      [23.90379306, 121.53615306],
                      [23.90376639, 121.53642389],
                      [23.90339194, 121.53638639]], dtype=np.float128)
#pts_gps = (pts_gps_old - np.float32([23.903, 121.535])) * 5000000
print pts_gps
pts_xys = np.array([[876, 364],
                      [51, 788],
                      [1911, 745],
                      [1066, 376],
                      [148, 396],
                      [910, 958],
                      [678, 454],
                      [417, 540],
                      [615, 456],
                      [1077, 475],
                      [1554, 503],
                      [1036, 809],
                      [55, 448]], dtype=np.float128)

[[ 23.90344056 121.53592722]
 [ 23.90368083 121.53650361]
 [ 23.90387389 121.53634472]
 [ 23.90353583 121.53588083]
 [ 23.90325667 121.53627833]
 [ 23.90377194 121.53645972]
 [ 23.90356778 121.53624333]
 [ 23.90360417 121.53637861]
 [ 23.90355778 121.53626361]
 [ 23.90367083 121.53619194]
 [ 23.90379306 121.53615306]
 [ 23.90376639 121.53642389]
 [ 23.90339194 121.53638639]]


In [3]:
# input four pairs of the corresponding points, find out perspective transformation matrix M

In [4]:
pts1 = np.array([pts_gps[0], pts_gps[1], pts_gps[2], pts_gps[3], pts_gps[4], pts_gps[5], pts_gps[6], pts_gps[7], pts_gps[8], pts_gps[9], pts_gps[10], pts_gps[11], pts_gps[12]], dtype=np.float64)
pts2 = np.array([pts_xys[0], pts_xys[1], pts_xys[2], pts_xys[3], pts_xys[4], pts_xys[5], pts_xys[6], pts_xys[7], pts_xys[8], pts_xys[9], pts_xys[10], pts_xys[11], pts_xys[12]], dtype=np.float64)

In [5]:
M, mask = cv2.findHomography(pts1, pts2)
print M

[[ 5.01641116 -12.50545408  1399.95859355]
 [-1.35042868 -1.81213765  252.52228455]
 [-0.00536118 -0.00717354  1.00000000]]


In [6]:
def compute_gps2xy(idx):
    print("input %.10f, %.10f " % (pts_gps[idx, 0], pts_gps[idx, 1]))
    expect_result = np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    print("input gps: ", np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T)
    result_pre = np.matrix(M) * np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_xy: ", result)
    diff = result - expect_result
    print("diff_xy: ", diff)

In [7]:
#驗證 gps -> xy for point 0
#compute_gps2xy(0)

In [8]:
#驗證 gps -> xy for point 1
#compute_gps2xy(1)

In [9]:
#驗證 gps -> xy for point 2
#compute_gps2xy(2)

In [10]:
#驗證 gps -> xy for point 3
#compute_gps2xy(3)

In [11]:
#驗證 gps -> xy for point 4
#compute_gps2xy(4)

In [12]:
#驗證 gps -> xy for point 5
#compute_gps2xy(5)

In [13]:
#驗證 gps -> xy for point 6
#compute_gps2xy(6)

In [14]:
#驗證 gps -> xy for point 7
#compute_gps2xy(7)

In [15]:
#驗證 gps -> xy for point 8
#compute_gps2xy(8)

In [16]:
#驗證 gps -> xy for point 9
#compute_gps2xy(9)

In [17]:
#驗證 gps -> xy for point 10
#compute_gps2xy(10)

In [18]:
#驗證 gps -> xy for point 11
#compute_gps2xy(11)

In [19]:
#驗證 gps -> xy for point 12
#compute_gps2xy(12)

In [20]:
# inverse Transform
inv_M = np.linalg.inv(M) 
print inv_M


[[-7.74900426  28928.80570501 -7294319.82077932]
 [-39.80502987  147085.43522319 -37086624.73273041]
 [-0.32708666  1210.21534510 -305147.43595814]]


In [21]:
def compute_xy2gps(idx):
    expect_result = np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    print("input xy: ", np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T)
    result_pre = np.matrix(inv_M) * np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_gps: ", result)
    diff = result - expect_result
    print("diff_gps: ", diff)

In [22]:
#驗證 xy -> gps for point 0
compute_xy2gps(0)

('input xy: ', matrix([[876.],
        [364.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90340268],
        [121.53588305],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-3.78844579e-05],
        [-4.41734685e-05],
        [ 0.00000000e+00]], dtype=float128))


In [23]:
#驗證 xy -> gps for point 1
compute_xy2gps(1)

('input xy: ', matrix([[ 51.],
        [788.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.903668  ],
        [121.53650175],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-1.28323369e-05],
        [-1.86112877e-06],
        [ 0.00000000e+00]], dtype=float128))


In [24]:
#驗證 xy -> gps for point 2
compute_xy2gps(2)

('input xy: ', matrix([[1.911e+03],
        [7.450e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.90386929],
        [121.53633232],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-4.59806665e-06],
        [-1.24034706e-05],
        [ 0.00000000e+00]], dtype=float128))


In [25]:
#驗證 xy -> gps for point 3
compute_xy2gps(3)

('input xy: ', matrix([[1.066e+03],
        [3.760e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.90353436],
        [121.53588442],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-1.46804884e-06],
        [ 3.58640975e-06],
        [ 0.00000000e+00]], dtype=float128))


In [26]:
#驗證 xy -> gps for point 4
compute_xy2gps(4)

('input xy: ', matrix([[148.],
        [396.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90321152],
        [121.53625693],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-4.51458158e-05],
        [-2.13980705e-05],
        [ 0.00000000e+00]], dtype=float128))


In [27]:
#驗證 xy -> gps for point 5
compute_xy2gps(5)

('input xy: ', matrix([[910.],
        [958.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90378175],
        [121.53646845],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[9.81151194e-06],
        [8.73409664e-06],
        [0.00000000e+00]], dtype=float128))


In [28]:
#驗證 xy -> gps for point 6
compute_xy2gps(6)

('input xy: ', matrix([[678.],
        [454.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.9035458 ],
        [121.53623688],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-2.19815240e-05],
        [-6.44672127e-06],
        [ 0.00000000e+00]], dtype=float128))


In [29]:
#驗證 xy -> gps for point 7
compute_xy2gps(7)

('input xy: ', matrix([[417.],
        [540.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90358452],
        [121.53637879],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-1.96548975e-05],
        [ 1.83395534e-07],
        [ 0.00000000e+00]], dtype=float128))


In [30]:
#驗證 xy -> gps for point 8
compute_xy2gps(8)

('input xy: ', matrix([[615.],
        [456.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90353101],
        [121.53625359],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-2.67664583e-05],
        [-1.00213072e-05],
        [ 0.00000000e+00]], dtype=float128))


In [31]:
#驗證 xy -> gps for point 9
compute_xy2gps(9)

('input xy: ', matrix([[1.077e+03],
        [4.750e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.90367746],
        [121.5361921 ],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[6.63413802e-06],
        [1.56450220e-07],
        [0.00000000e+00]], dtype=float128))


In [32]:
#驗證 xy -> gps for point 10
compute_xy2gps(10)

('input xy: ', matrix([[1.554e+03],
        [5.030e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.90380621],
        [121.53615347],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[1.31509847e-05],
        [4.13978581e-07],
        [0.00000000e+00]], dtype=float128))


In [33]:
#驗證 xy -> gps for point 11
compute_xy2gps(11)

('input xy: ', matrix([[1.036e+03],
        [8.090e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.90377658],
        [121.5364286 ],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[1.01932864e-05],
        [4.71476429e-06],
        [0.00000000e+00]], dtype=float128))


In [34]:
#驗證 xy -> gps for point 12
compute_xy2gps(12)

('input xy: ', matrix([[ 55.],
        [448.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90335373],
        [121.53636342],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-3.8207713e-05],
        [-2.2972472e-05],
        [ 0.0000000e+00]], dtype=float128))


In [35]:
#img = cv2.imread('1010.jpg', cv2.IMREAD_COLOR)
#imgReg = cv2.warpPerspective(img, inv_M, (10000, 10000))
#cv2.imwrite("1010_reg.jpg", imgReg)
#cv2.namedWindow("1010.jpg")
#cv2.imshow("1010.jpg", img)
#cv2.waitKey(0)