In [1]:
import cv2
import numpy as np
import datetime
np.set_printoptions(formatter={'float': '{: 0.8f}'.format})

In [2]:
pts_gps_old = np.array([[2390344.056, 12153592.722], 
                      [2390368.083, 12153650.361], 
                      [2390387.389, 12153634.472],
                      [2390353.583, 12153588.083],
                      [2390325.667, 12153627.833],
                      [2390377.194, 12153645.972],
                      [2390356.778, 12153624.333],
                      [2390360.417, 12153637.861],
                      [2390355.778, 12153626.361],
                      [2390367.083, 12153619.194],
                      [2390379.306, 12153615.306],
                      [2390376.639, 12153642.389],
                      [2390339.194, 12153638.639]], dtype=np.float128)
# pts_gps = (pts_gps_old - np.float64([2390300.0, 12153500.0])) * 100.0
pts_gps = pts_gps_old
print pts_gps
pts_xys = np.array([[876, 364],
                      [51, 788],
                      [1911, 745],
                      [1066, 376],
                      [148, 396],
                      [910, 958],
                      [678, 454],
                      [417, 540],
                      [615, 456],
                      [1077, 475],
                      [1554, 503],
                      [1036, 809],
                      [55, 448]], dtype=np.float128)

[[ 2390344.056 12153592.722]
 [ 2390368.083 12153650.361]
 [ 2390387.389 12153634.472]
 [ 2390353.583 12153588.083]
 [ 2390325.667 12153627.833]
 [ 2390377.194 12153645.972]
 [ 2390356.778 12153624.333]
 [ 2390360.417 12153637.861]
 [ 2390355.778 12153626.361]
 [ 2390367.083 12153619.194]
 [ 2390379.306 12153615.306]
 [ 2390376.639 12153642.389]
 [ 2390339.194 12153638.639]]


In [3]:
# input four pairs of the corresponding points, find out perspective transformation matrix M

In [4]:
pts1 = np.array([pts_gps[0], pts_gps[1], pts_gps[2], pts_gps[3], pts_gps[4], pts_gps[5], pts_gps[6], pts_gps[7], pts_gps[8], pts_gps[9], pts_gps[10], pts_gps[11], pts_gps[12]], dtype=np.float64)
pts2 = np.array([pts_xys[0], pts_xys[1], pts_xys[2], pts_xys[3], pts_xys[4], pts_xys[5], pts_xys[6], pts_xys[7], pts_xys[8], pts_xys[9], pts_xys[10], pts_xys[11], pts_xys[12]], dtype=np.float64)

In [5]:
M, mask = cv2.findHomography(pts1, pts2)
print M
print M.dtype

[[ 0.00004821 -0.00012468  1400.11503077]
 [-0.00001332 -0.00001826  253.79214344]
 [-0.00000006 -0.00000007  1.00000000]]
float64


In [6]:
def compute_gps2xy(idx):
    print("input %.10f, %.10f " % (pts_gps[idx, 0], pts_gps[idx, 1]))
    expect_result = np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    print("input gps: ", np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T)
    result_pre = np.matrix(M) * np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_xy: ", result)
    diff = result - expect_result
    print("diff_xy: ", diff)

In [7]:
#驗證 gps -> xy for point 0
#compute_gps2xy(0)

In [8]:
#驗證 gps -> xy for point 1
#compute_gps2xy(1)

In [9]:
#驗證 gps -> xy for point 2
#compute_gps2xy(2)

In [10]:
#驗證 gps -> xy for point 3
#compute_gps2xy(3)

In [11]:
#驗證 gps -> xy for point 4
#compute_gps2xy(4)

In [12]:
#驗證 gps -> xy for point 5
#compute_gps2xy(5)

In [13]:
#驗證 gps -> xy for point 6
#compute_gps2xy(6)

In [14]:
#驗證 gps -> xy for point 7
#compute_gps2xy(7)

In [15]:
#驗證 gps -> xy for point 8
#compute_gps2xy(8)

In [16]:
#驗證 gps -> xy for point 9
#compute_gps2xy(9)

In [17]:
#驗證 gps -> xy for point 10
#compute_gps2xy(10)

In [18]:
#驗證 gps -> xy for point 11
#compute_gps2xy(11)

In [19]:
#驗證 gps -> xy for point 12
#compute_gps2xy(12)

In [20]:
# inverse Transform
inv_M = np.linalg.inv(M) 
print inv_M


[[-22645238.08514558  2936054985.30354309 -713441749765.16479492]
 [-115177315.84607926  14928059211.99946785 -3627362653721.51855469]
 [-9.47631860  1228.27712534 -298458.14827677]]


In [21]:
def compute_xy2gps(idx):
    expect_result = np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    print("input xy: ", np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T)
    result_pre = np.matrix(inv_M) * np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_gps: ", result)
    diff = result - expect_result
    print("diff_gps: ", diff)

In [22]:
#驗證 xy -> gps for point 0
compute_xy2gps(0)

('input xy: ', matrix([[876.],
        [364.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[2.39034234e+06],
        [1.21535908e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[-1.71136131],
        [-1.9381678 ],
        [ 0.        ]], dtype=float128))


In [23]:
#驗證 xy -> gps for point 1
compute_xy2gps(1)

('input xy: ', matrix([[ 51.],
        [788.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[2.3903675e+06],
        [1.2153650e+07],
        [1.0000000e+00]], dtype=float128))
('diff_gps: ', matrix([[-0.57869489],
        [-0.39571892],
        [ 0.        ]], dtype=float128))


In [24]:
#驗證 xy -> gps for point 2
compute_xy2gps(2)

('input xy: ', matrix([[1.911e+03],
        [7.450e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[2.39038663e+06],
        [1.21536324e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[-0.75793988],
        [-2.10927123],
        [ 0.        ]], dtype=float128))


In [25]:
#驗證 xy -> gps for point 3
compute_xy2gps(3)

('input xy: ', matrix([[1.066e+03],
        [3.760e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[2.39035437e+06],
        [1.21535897e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[0.7884057 ],
        [1.63485994],
        [0.        ]], dtype=float128))


In [26]:
#驗證 xy -> gps for point 4
compute_xy2gps(4)

('input xy: ', matrix([[148.],
        [396.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[2.39032629e+06],
        [1.21536283e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[0.61913063],
        [0.44415396],
        [0.        ]], dtype=float128))


In [27]:
#驗證 xy -> gps for point 5
compute_xy2gps(5)

('input xy: ', matrix([[910.],
        [958.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[2.39037823e+06],
        [1.21536463e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[1.03103839],
        [0.35678379],
        [0.        ]], dtype=float128))


In [28]:
#驗證 xy -> gps for point 6
compute_xy2gps(6)

('input xy: ', matrix([[678.],
        [454.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[2.39035590e+06],
        [1.21536246e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[-0.87927895],
        [ 0.24246754],
        [ 0.        ]], dtype=float128))


In [29]:
#驗證 xy -> gps for point 7
compute_xy2gps(7)

('input xy: ', matrix([[417.],
        [540.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[2.39035963e+06],
        [1.21536383e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[-0.7820051 ],
        [ 0.40510317],
        [ 0.        ]], dtype=float128))


In [30]:
#驗證 xy -> gps for point 8
compute_xy2gps(8)

('input xy: ', matrix([[615.],
        [456.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[2.39035457e+06],
        [1.21536263e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[-1.21128895],
        [-0.06846704],
        [ 0.        ]], dtype=float128))


In [31]:
#驗證 xy -> gps for point 9
compute_xy2gps(9)

('input xy: ', matrix([[1.077e+03],
        [4.750e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[2.39036810e+06],
        [1.21536194e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[1.02107893],
        [0.17731435],
        [0.        ]], dtype=float128))


In [32]:
#驗證 xy -> gps for point 10
compute_xy2gps(10)

('input xy: ', matrix([[1.554e+03],
        [5.030e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[2.39038041e+06],
        [1.21536147e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[ 1.09933413],
        [-0.65427282],
        [ 0.        ]], dtype=float128))


In [33]:
#驗證 xy -> gps for point 11
compute_xy2gps(11)

('input xy: ', matrix([[1.036e+03],
        [8.090e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[2.39037771e+06],
        [1.21536424e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[1.06764647],
        [0.00926732],
        [0.        ]], dtype=float128))


In [34]:
#驗證 xy -> gps for point 12
compute_xy2gps(12)

('input xy: ', matrix([[ 55.],
        [448.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[2.39033885e+06],
        [1.21536377e+07],
        [1.00000000e+00]], dtype=float128))
('diff_gps: ', matrix([[-0.3473348],
        [-0.8975702],
        [ 0.       ]], dtype=float128))


In [35]:
#img = cv2.imread('1010.jpg', cv2.IMREAD_COLOR)
#imgReg = cv2.warpPerspective(img, inv_M, (20000, 20000))
#cv2.imwrite("1010_reg_new.jpg", imgReg)
#cv2.namedWindow("1010.jpg")
#cv2.imshow("1010.jpg", img)
#cv2.waitKey(0)