In [1]:
import cv2
import numpy as np
import datetime
np.set_printoptions(formatter={'float': '{: 0.8f}'.format})

In [2]:
pts_gps = np.array([[23.90344056, 121.53592722], 
                      [23.90368083, 121.53650361], 
                      [23.90387389, 121.53634472],
                      [23.90353583, 121.53588083],
                      [23.90325667, 121.53627833],
                      [23.90377194, 121.53645972],
                      [23.90356778, 121.53624333],
                      [23.90360417, 121.53637861],
                      [23.90355778, 121.53626361],
                      [23.90367083, 121.53619194],
                      [23.90379306, 121.53615306],
                      [23.90376639, 121.53642389],
                      [23.90339194, 121.53638639]], dtype=np.float128)

print pts_gps
pts_xys = np.array([[876, 364],
                      [51, 788],
                      [1911, 745],
                      [1066, 376],
                      [148, 396],
                      [910, 958],
                      [678, 454],
                      [417, 540],
                      [615, 456],
                      [1077, 475],
                      [1554, 503],
                      [1036, 809],
                      [55, 448]], dtype=np.float128)

[[ 23.90344056 121.53592722]
 [ 23.90368083 121.53650361]
 [ 23.90387389 121.53634472]
 [ 23.90353583 121.53588083]
 [ 23.90325667 121.53627833]
 [ 23.90377194 121.53645972]
 [ 23.90356778 121.53624333]
 [ 23.90360417 121.53637861]
 [ 23.90355778 121.53626361]
 [ 23.90367083 121.53619194]
 [ 23.90379306 121.53615306]
 [ 23.90376639 121.53642389]
 [ 23.90339194 121.53638639]]


In [3]:
# input four pairs of the corresponding points, find out perspective transformation matrix M

In [4]:
pts1 = np.array([pts_gps[6], pts_gps[8], pts_gps[7], pts_gps[11], pts_gps[9]], dtype=np.float64)
pts2 = np.array([pts_xys[6], pts_xys[8], pts_xys[7], pts_xys[11], pts_xys[9]], dtype=np.float64)

In [5]:
M, mask = cv2.findHomography(pts1, pts2)
print M

[[ 6.23934771 -13.29129504  1466.23418492]
 [-1.48259197 -1.65821972  236.97490934]
 [-0.00655396 -0.00693894  1.00000000]]


In [6]:
def compute_gps2xy(idx):
    print("input %.10f, %.10f " % (pts_gps[idx, 0], pts_gps[idx, 1]))
    expect_result = np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    print("input gps: ", np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T)
    result_pre = np.matrix(M) * np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_xy: ", result)
    diff = result - expect_result
    print("diff_xy: ", diff)

In [7]:
#驗證 gps -> xy for point 0
#compute_gps2xy(0)

In [8]:
#驗證 gps -> xy for point 1
#compute_gps2xy(1)

In [9]:
#驗證 gps -> xy for point 2
#compute_gps2xy(2)

In [10]:
#驗證 gps -> xy for point 3
#compute_gps2xy(3)

In [11]:
#驗證 gps -> xy for point 4
#compute_gps2xy(4)

In [12]:
#驗證 gps -> xy for point 5
#compute_gps2xy(5)

In [13]:
#驗證 gps -> xy for point 6
#compute_gps2xy(6)

In [14]:
#驗證 gps -> xy for point 7
#compute_gps2xy(7)

In [15]:
#驗證 gps -> xy for point 8
#compute_gps2xy(8)

In [16]:
#驗證 gps -> xy for point 9
#compute_gps2xy(9)

In [17]:
#驗證 gps -> xy for point 10
#compute_gps2xy(10)

In [18]:
#驗證 gps -> xy for point 11
#compute_gps2xy(11)

In [19]:
#驗證 gps -> xy for point 12
#compute_gps2xy(12)

In [20]:
# inverse Transform
inv_M = np.linalg.inv(M) 
print inv_M


[[-116.68354737  26233.41703686 -6045576.21796273]
 [-593.58610612  133381.06764748 -30737630.17265373]
 [-4.88359835  1097.45614253 -252908.07103202]]


In [21]:
def compute_xy2gps(idx):
    expect_result = np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    print("input xy: ", np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T)
    result_pre = np.matrix(inv_M) * np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_gps: ", result)
    diff = result - expect_result
    print("diff_gps: ", diff)

In [22]:
#驗證 xy -> gps for point 0
compute_xy2gps(0)

('input xy: ', matrix([[876.],
        [364.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90345219],
        [121.53593558],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[1.16272594e-05],
        [8.36305077e-06],
        [0.00000000e+00]], dtype=float128))


In [23]:
#驗證 xy -> gps for point 1
compute_xy2gps(1)

('input xy: ', matrix([[ 51.],
        [788.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90367871],
        [121.53649885],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-2.12247315e-06],
        [-4.76455881e-06],
        [ 0.00000000e+00]], dtype=float128))


In [24]:
#驗證 xy -> gps for point 2
compute_xy2gps(2)

('input xy: ', matrix([[1.911e+03],
        [7.450e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.90384048],
        [121.53632217],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-3.34075676e-05],
        [-2.25490450e-05],
        [ 0.00000000e+00]], dtype=float128))


In [25]:
#驗證 xy -> gps for point 3
compute_xy2gps(3)

('input xy: ', matrix([[1.066e+03],
        [3.760e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.90354841],
        [121.53592494],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[1.25758282e-05],
        [4.41079953e-05],
        [0.00000000e+00]], dtype=float128))


In [26]:
#驗證 xy -> gps for point 4
compute_xy2gps(4)

('input xy: ', matrix([[148.],
        [396.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.9033212 ],
        [121.53627576],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[ 6.45286383e-05],
        [-2.56980802e-06],
        [ 0.00000000e+00]], dtype=float128))


In [27]:
#驗證 xy -> gps for point 5
compute_xy2gps(5)

('input xy: ', matrix([[910.],
        [958.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90377353],
        [121.5364634 ],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[1.58897353e-06],
        [3.68318499e-06],
        [0.00000000e+00]], dtype=float128))


In [28]:
#驗證 xy -> gps for point 6
compute_xy2gps(6)

('input xy: ', matrix([[678.],
        [454.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90356885],
        [121.53624278],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[ 1.06724506e-06],
        [-5.48886061e-07],
        [ 0.00000000e+00]], dtype=float128))


In [29]:
#驗證 xy -> gps for point 7
compute_xy2gps(7)

('input xy: ', matrix([[417.],
        [540.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90360479],
        [121.53637751],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[ 6.17689918e-07],
        [-1.10106980e-06],
        [ 0.00000000e+00]], dtype=float128))


In [30]:
#驗證 xy -> gps for point 8
compute_xy2gps(8)

('input xy: ', matrix([[615.],
        [456.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.90355792],
        [121.53625919],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[ 1.42500187e-07],
        [-4.41624365e-06],
        [ 0.00000000e+00]], dtype=float128))


In [31]:
#驗證 xy -> gps for point 9
compute_xy2gps(9)

('input xy: ', matrix([[1.077e+03],
        [4.750e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.90367135],
        [121.53619371],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[5.20407484e-07],
        [1.76972656e-06],
        [0.00000000e+00]], dtype=float128))


In [32]:
#驗證 xy -> gps for point 10
compute_xy2gps(10)

('input xy: ', matrix([[1.554e+03],
        [5.030e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.90377493],
        [121.53614923],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[-1.81265819e-05],
        [-3.83072467e-06],
        [ 0.00000000e+00]], dtype=float128))


In [33]:
#驗證 xy -> gps for point 11
compute_xy2gps(11)

('input xy: ', matrix([[1.036e+03],
        [8.090e+02],
        [1.000e+00]], dtype=float128))
('output_gps: ', matrix([[ 23.90376661],
        [121.53642264],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[ 2.24639273e-07],
        [-1.25280879e-06],
        [ 0.00000000e+00]], dtype=float128))


In [34]:
#驗證 xy -> gps for point 12
compute_xy2gps(12)

('input xy: ', matrix([[ 55.],
        [448.],
        [  1.]], dtype=float128))
('output_gps: ', matrix([[ 23.9034258 ],
        [121.53636905],
        [  1.        ]], dtype=float128))
('diff_gps: ', matrix([[ 3.38620342e-05],
        [-1.73442835e-05],
        [ 0.00000000e+00]], dtype=float128))


In [35]:
#img = cv2.imread('1010.jpg', cv2.IMREAD_COLOR)
#imgReg = cv2.warpPerspective(img, inv_M, (10000, 10000))
#cv2.imwrite("1010_reg.jpg", imgReg)
#cv2.namedWindow("1010.jpg")
#cv2.imshow("1010.jpg", img)
#cv2.waitKey(0)