In [1]:
import cv2
import numpy as np
import datetime
np.set_printoptions(precision=10)

In [2]:
pts_gps_old = np.array([[23.90344056, 121.53592722], 
                      [23.90368083, 121.53650361], 
                      [23.90387389, 121.53634472],
                      [23.90353583, 121.53588083],
                      [23.90325667, 121.53627833],
                      [23.90377194, 121.53645972],
                      [23.90356778, 121.53624333],
                      [23.90360417, 121.53637861],
                      [23.90355778, 121.53626361],
                      [23.90367083, 121.53619194],
                      [23.90379306, 121.53615306],
                      [23.90376639, 121.53642389],
                      [23.90339194, 121.53638639]], dtype=np.float32)
pts_gps = (pts_gps_old - np.float32([23.903, 121.535])) * 5000000
print pts_gps
pts_xys = np.array([[876, 364],
                      [51, 788],
                      [1911, 745],
                      [1066, 376],
                      [148, 396],
                      [910, 958],
                      [678, 454],
                      [417, 540],
                      [615, 456],
                      [1077, 475],
                      [1554, 503],
                      [1036, 809],
                      [55, 448]], dtype=np.float32)

[[2202.9876708984 4615.7836914062]
 [3404.6173095703 7514.9536132812]
 [4367.8283691406 6713.8671875   ]
 [2679.8248291016 4386.9018554688]
 [1287.4603271484 6370.5444335938]
 [3862.3809814453 7286.0717773438]
 [2841.9494628906 6179.8095703125]
 [3023.1475830078 6866.455078125 ]
 [2794.2657470703 6294.2504882812]
 [3356.93359375   5950.927734375 ]
 [3967.28515625   5760.1928710938]
 [3833.7707519531 7095.3369140625]
 [1964.5690917969 6904.6020507812]]


In [3]:
# input four pairs of the corresponding points, find out perspective transformation matrix M

In [4]:
pts1 = np.array([pts_gps[0], pts_gps[1], pts_gps[2], pts_gps[3], pts_gps[4], pts_gps[5], pts_gps[6], pts_gps[7], pts_gps[8], pts_gps[9], pts_gps[10], pts_gps[11], pts_gps[12]], dtype=np.float32)
pts2 = np.array([pts_xys[0], pts_xys[1], pts_xys[2], pts_xys[3], pts_xys[4], pts_xys[5], pts_xys[6], pts_xys[7], pts_xys[8], pts_xys[9], pts_xys[10], pts_xys[11], pts_xys[12]], dtype=np.float32)

In [5]:
M, mask = cv2.findHomography(pts1, pts2)
print M

[[ 6.8185309327e-02 -1.5866880821e-01  9.6554595092e+02]
 [-1.3661926651e-02 -2.4008346097e-02  3.0123488101e+02]
 [-6.4219450354e-05 -9.2019669024e-05  1.0000000000e+00]]


In [6]:
def compute_gps2xy(idx):
    print("input %.10f, %.10f " % (pts_gps[idx, 0], pts_gps[idx, 1]))
    expect_result = np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    print("input gps: ", np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T)
    result_pre = np.matrix(M) * np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_xy: ", result)
    diff = result - expect_result
    print("diff_xy: ", diff)

In [7]:
#驗證 gps -> xy for point 0
#compute_gps2xy(0)

In [8]:
#驗證 gps -> xy for point 1
#compute_gps2xy(1)

In [9]:
#驗證 gps -> xy for point 2
#compute_gps2xy(2)

In [10]:
#驗證 gps -> xy for point 3
#compute_gps2xy(3)

In [11]:
#驗證 gps -> xy for point 4
#compute_gps2xy(4)

In [12]:
#驗證 gps -> xy for point 5
#compute_gps2xy(5)

In [13]:
#驗證 gps -> xy for point 6
#compute_gps2xy(6)

In [14]:
#驗證 gps -> xy for point 7
#compute_gps2xy(7)

In [15]:
#驗證 gps -> xy for point 8
#compute_gps2xy(8)

In [16]:
#驗證 gps -> xy for point 9
#compute_gps2xy(9)

In [17]:
#驗證 gps -> xy for point 10
#compute_gps2xy(10)

In [18]:
#驗證 gps -> xy for point 11
#compute_gps2xy(11)

In [19]:
#驗證 gps -> xy for point 12
#compute_gps2xy(12)

In [20]:
# inverse Transform
inv_M = np.linalg.inv(M) 
print inv_M


[[ 4.2174171097e+00  7.9343416365e+01 -2.7973114601e+04]
 [-6.4584373374e+00  1.4795115855e+02 -3.8332131621e+04]
 [-3.2346305750e-04  1.8709807230e-02 -4.3237281091e+00]]


In [21]:
def compute_xy2gps(idx):
    expect_result = np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    print("input xy: ", np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T)
    result_pre = np.matrix(inv_M) * np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_gps: ", result)
    diff = result - expect_result
    print("diff_gps: ", diff)

In [22]:
#驗證 xy -> gps for point 0
compute_xy2gps(0)

('input xy: ', matrix([[876.],
        [364.],
        [  1.]]))
('output_gps: ', matrix([[2.0888536441e+03],
        [4.4771716667e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[-114.1340267534],
        [-138.6120247116],
        [   0.          ]]))


In [23]:
#驗證 xy -> gps for point 1
compute_xy2gps(1)

('input xy: ', matrix([[ 51.],
        [788.],
        [  1.]]))
('output_gps: ', matrix([[3.341751449e+03],
        [7.490457244e+03],
        [1.000000000e+00]]))
('diff_gps: ', matrix([[-62.8658605851],
        [-24.49636927  ],
        [  0.          ]]))


In [24]:
#驗證 xy -> gps for point 2
compute_xy2gps(2)

('input xy: ', matrix([[1.911e+03],
        [7.450e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[4.3567271825e+03],
        [6.6188509950e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[-11.1011866089],
        [-95.016192492 ],
        [  0.          ]]))


In [25]:
#驗證 xy -> gps for point 3
compute_xy2gps(3)

('input xy: ', matrix([[1.066e+03],
        [3.760e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[2.6859012939e+03],
        [4.4003716768e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[ 6.0764648071],
        [13.4698212948],
        [ 0.          ]]))


In [26]:
#驗證 xy -> gps for point 4
compute_xy2gps(4)

('input xy: ', matrix([[148.],
        [396.],
        [  1.]]))
('output_gps: ', matrix([[1.3402728453e+03],
        [6.3541683373e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[ 52.8125181092],
        [-16.3760963296],
        [  0.          ]]))


In [27]:
#驗證 xy -> gps for point 5
compute_xy2gps(5)

('input xy: ', matrix([[910.],
        [958.],
        [  1.]]))
('output_gps: ', matrix([[3.8986965265e+03],
        [7.3296646022e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[36.3155450774],
        [43.5928248978],
        [ 0.          ]]))


In [28]:
#驗證 xy -> gps for point 6
compute_xy2gps(6)

('input xy: ', matrix([[678.],
        [454.],
        [  1.]]))
('output_gps: ', matrix([[2.7607207677e+03],
        [6.1902136571e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[-81.228695202 ],
        [ 10.4040867479],
        [  0.          ]]))


In [29]:
#驗證 xy -> gps for point 7
compute_xy2gps(7)

('input xy: ', matrix([[417.],
        [540.],
        [  1.]]))
('output_gps: ', matrix([[2.9463109104e+03],
        [6.8858288069e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[-76.8366726539],
        [ 19.3737287268],
        [  0.          ]]))


In [30]:
#驗證 xy -> gps for point 8
compute_xy2gps(8)

('input xy: ', matrix([[615.],
        [456.],
        [  1.]]))
('output_gps: ', matrix([[2.6942271155e+03],
        [6.2762705280e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[-100.0386315678],
        [ -17.9799602337],
        [   0.          ]]))


In [31]:
#驗證 xy -> gps for point 9
compute_xy2gps(9)

('input xy: ', matrix([[1.077e+03],
        [4.750e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[3.3824344918e+03],
        [5.9284869135e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[ 25.500898059],
        [-22.4408209  ],
        [  0.         ]]))


In [32]:
#驗證 xy -> gps for point 10
compute_xy2gps(10)

('input xy: ', matrix([[1.554e+03],
        [5.030e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[4.0331359854e+03],
        [5.6822063567e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[ 65.8508291482],
        [-77.9865143595],
        [  0.          ]]))


In [33]:
#驗證 xy -> gps for point 11
compute_xy2gps(11)

('input xy: ', matrix([[1.036e+03],
        [8.090e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[3.8735717152e+03],
        [7.1267134314e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[39.8009632958],
        [31.3765173599],
        [ 0.          ]]))


In [34]:
#驗證 xy -> gps for point 12
compute_xy2gps(12)

('input xy: ', matrix([[ 55.],
        [448.],
        [  1.]]))
('output_gps: ', matrix([[1.9316277795e+03],
        [6.8295863569e+03],
        [1.0000000000e+00]]))
('diff_gps: ', matrix([[-32.9413123369],
        [-75.0156939113],
        [  0.          ]]))


In [38]:
img = cv2.imread('1010.jpg', cv2.IMREAD_COLOR)
imgReg = cv2.warpPerspective(img, inv_M, (10000, 10000))
cv2.imwrite("1010_reg.jpg", imgReg)
#cv2.namedWindow("1010.jpg")
#cv2.imshow("1010.jpg", img)
#cv2.waitKey(0)

True