In [1]:
import cv2
import numpy as np
import datetime
np.set_printoptions(precision=10)

In [2]:
pts_gps = np.array([[23.90344056, 121.53592722], 
                      [23.90368083, 121.53650361], 
                      [23.90387389, 121.53634472],
                      [23.90353583, 121.53588083],
                      [23.90325667, 121.53627833],
                      [23.90377194, 121.53645972],
                      [23.90356778, 121.53624333],
                      [23.90360417, 121.53637861],
                      [23.90355778, 121.53626361],
                      [23.90367083, 121.53619194],
                      [23.90379306, 121.53615306],
                      [23.90376639, 121.53642389],
                      [23.90339194, 121.53638639]], dtype=np.float32)
pts_xys = np.array([[876, 364],
                      [51, 788],
                      [1911, 745],
                      [1066, 376],
                      [148, 396],
                      [910, 958],
                      [678, 454],
                      [417, 540],
                      [615, 456],
                      [1077, 475],
                      [1554, 503],
                      [1036, 809],
                      [55, 448]], dtype=np.float32)

In [3]:
# input four pairs of the corresponding points, find out perspective transformation matrix M

In [4]:
pts1 = np.array([pts_gps[0], pts_gps[1], pts_gps[2], pts_gps[3], pts_gps[4], pts_gps[5], pts_gps[6], pts_gps[7], pts_gps[8], pts_gps[9], pts_gps[10], pts_gps[11], pts_gps[12]], dtype=np.float32)
pts2 = np.array([pts_xys[0], pts_xys[1], pts_xys[2], pts_xys[3], pts_xys[4], pts_xys[5], pts_xys[6], pts_xys[7], pts_xys[8], pts_xys[9], pts_xys[10], pts_xys[11], pts_xys[12]], dtype=np.float32)

In [5]:
M, mask = cv2.findHomography(pts1, pts2, cv2.RANSAC, 5.0)
print M

[[ 5.6526219168e+00 -1.3732664766e+01  1.5339018564e+03]
 [-1.5693472241e+00 -1.6452984433e+00  2.3747856374e+02]
 [-6.5657897431e-03 -6.9366091865e-03  1.0000000000e+00]]


In [6]:
def compute_gps2xy(idx):
    print("input %.10f, %.10f " % (pts_gps[idx, 0], pts_gps[idx, 1]))
    expect_result = np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    print("input gps: ", np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T)
    result_pre = np.matrix(M) * np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_xy: ", result)
    diff = result - expect_result
    print("diff_xy: ", diff)

In [7]:
#驗證 gps -> xy for point 0
compute_gps2xy(0)

input 23.9034404755, 121.5359268188 
('input gps: ', matrix([[ 23.9034404755],
        [121.5359268188],
        [  1.          ]]))
('output_xy: ', matrix([[874.3414211959],
        [370.6606865826],
        [  1.          ]]))
('diff_xy: ', matrix([[-1.6585788041],
        [ 6.6606865826],
        [ 0.          ]]))


In [8]:
#驗證 gps -> xy for point 1
compute_gps2xy(1)

input 23.9036808014, 121.5365066528 
('input gps: ', matrix([[ 23.9036808014],
        [121.5365066528],
        [  1.          ]]))
('output_xy: ', matrix([[101.2768970324],
        [707.679205997 ],
        [  1.          ]]))
('diff_xy: ', matrix([[ 50.2768970324],
        [-80.320794003 ],
        [  0.          ]]))


In [9]:
#驗證 gps -> xy for point 2
compute_gps2xy(2)

input 23.9038734436, 121.5363464355 
('input gps: ', matrix([[ 23.9038734436],
        [121.5363464355],
        [  1.          ]]))
('output_xy: ', matrix([[1.7088188456e+03],
        [7.4168149236e+02],
        [1.0000000000e+00]]))
('diff_xy: ', matrix([[-202.181154439 ],
        [  -3.3185076444],
        [   0.          ]]))


In [10]:
#驗證 gps -> xy for point 3
compute_gps2xy(3)

input 23.9035358429, 121.5358810425 
('input gps: ', matrix([[ 23.9035358429],
        [121.5358810425],
        [  1.          ]]))
('output_xy: ', matrix([[1.0660000000e+03],
        [3.7600000001e+02],
        [1.0000000000e+00]]))
('diff_xy: ', matrix([[3.4754521039e-08],
        [7.8153448158e-09],
        [0.0000000000e+00]]))


In [11]:
#驗證 gps -> xy for point 4
compute_gps2xy(4)

input 23.9032573700, 121.5362777710 
('input gps: ', matrix([[ 23.90325737 ],
        [121.536277771],
        [  1.         ]]))
('output_xy: ', matrix([[148.0000000277],
        [396.000000008 ],
        [  1.          ]]))
('diff_xy: ', matrix([[2.7683626058e-08],
        [7.9674578046e-09],
        [0.0000000000e+00]]))


In [12]:
#驗證 gps -> xy for point 5
compute_gps2xy(5)

input 23.9037723541, 121.5364608765 
('input gps: ', matrix([[ 23.9037723541],
        [121.5364608765],
        [  1.          ]]))
('output_xy: ', matrix([[711.3934087144],
        [776.3959421768],
        [  1.          ]]))
('diff_xy: ', matrix([[-198.6065912856],
        [-181.6040578232],
        [   0.          ]]))


In [13]:
#驗證 gps -> xy for point 6
compute_gps2xy(6)

input 23.9035682678, 121.5362396240 
('input gps: ', matrix([[ 23.9035682678],
        [121.536239624 ],
        [  1.          ]]))
('output_xy: ', matrix([[678.0000000511],
        [454.0000000037],
        [  1.          ]]))
('diff_xy: ', matrix([[5.1066308515e-08],
        [3.7004497244e-09],
        [0.0000000000e+00]]))


In [14]:
#驗證 gps -> xy for point 7
compute_gps2xy(7)

input 23.9036045074, 121.5363769531 
('input gps: ', matrix([[ 23.9036045074],
        [121.5363769531],
        [  1.          ]]))
('output_xy: ', matrix([[435.9222470223],
        [525.3843306623],
        [  1.          ]]))
('diff_xy: ', matrix([[ 18.9222470223],
        [-14.6156693377],
        [  0.          ]]))


In [15]:
#驗證 gps -> xy for point 8
compute_gps2xy(8)

input 23.9035587311, 121.5362625122 
('input gps: ', matrix([[ 23.9035587311],
        [121.5362625122],
        [  1.          ]]))
('output_xy: ', matrix([[613.5826068345],
        [458.4557293718],
        [  1.          ]]))
('diff_xy: ', matrix([[-1.4173931655],
        [ 2.4557293718],
        [ 0.          ]]))


In [16]:
#驗證 gps -> xy for point 9
compute_gps2xy(9)

input 23.9036712646, 121.5361938477 
('input gps: ', matrix([[ 23.9036712646],
        [121.5361938477],
        [  1.          ]]))
('output_xy: ', matrix([[1.0053667698e+03],
        [4.7123192415e+02],
        [1.0000000000e+00]]))
('diff_xy: ', matrix([[-71.6332301582],
        [ -3.7680758516],
        [  0.          ]]))


In [17]:
#驗證 gps -> xy for point 10
compute_gps2xy(10)

input 23.9037933350, 121.5361557007 
('input gps: ', matrix([[ 23.903793335 ],
        [121.5361557007],
        [  1.          ]]))
('output_xy: ', matrix([[1.4544676719e+03],
        [5.0303564455e+02],
        [1.0000000000e+00]]))
('diff_xy: ', matrix([[-9.9532328146e+01],
        [ 3.5644552518e-02],
        [ 0.0000000000e+00]]))


In [18]:
#驗證 gps -> xy for point 11
compute_gps2xy(11)

input 23.9037666321, 121.5364227295 
('input gps: ', matrix([[ 23.9037666321],
        [121.5364227295],
        [  1.          ]]))
('output_xy: ', matrix([[835.5263296148],
        [703.2892507716],
        [  1.          ]]))
('diff_xy: ', matrix([[-200.4736703852],
        [-105.7107492284],
        [   0.          ]]))


In [19]:
#驗證 gps -> xy for point 12
compute_gps2xy(12)

input 23.9033927917, 121.5363845825 
('input gps: ', matrix([[ 23.9033927917],
        [121.5363845825],
        [  1.          ]]))
('output_xy: ', matrix([[ 55.0000000431],
        [448.0000000187],
        [  1.          ]]))
('diff_xy: ', matrix([[4.3111853643e-08],
        [1.8672096758e-08],
        [0.0000000000e+00]]))


In [20]:
# inverse Transform
inv_M = np.linalg.inv(M) 
print inv_M


[[ 1.4892641918e+01  2.3056715298e+04 -5.4983194845e+06]
 [ 7.5396550828e+01  1.1722918571e+05 -2.7955069558e+07]
 [ 6.2077836266e-01  9.6455859131e+02 -2.3001320199e+05]]


In [21]:
def compute_xy2gps(idx):
    expect_result = np.matrix([pts_gps[idx, 0], pts_gps[idx, 1], 1]).T
    print("input xy: ", np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T)
    result_pre = np.matrix(inv_M) * np.matrix([pts_xys[idx, 0], pts_xys[idx, 1], 1]).T
    result = result_pre / result_pre[2, 0]
    print("output_gps: ", result)
    diff = result - expect_result
    print("diff_gps: ", diff)

In [22]:
#驗證 xy -> gps for point 0
compute_xy2gps(0)

('input xy: ', matrix([[876.],
        [364.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9034167634],
        [121.5358898069],
        [  1.          ]]))
('diff_gps: ', matrix([[-2.3712077084e-05],
        [-3.7011958398e-05],
        [ 0.0000000000e+00]]))


In [23]:
#驗證 xy -> gps for point 1
compute_xy2gps(1)

('input xy: ', matrix([[ 51.],
        [788.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9037082224],
        [121.5365272267],
        [  1.          ]]))
('diff_gps: ', matrix([[2.7421032776e-05],
        [2.0573870700e-05],
        [0.0000000000e+00]]))


In [24]:
#驗證 xy -> gps for point 2
compute_xy2gps(2)

('input xy: ', matrix([[1.911e+03],
        [7.450e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[ 23.9038957796],
        [121.5363273064],
        [  1.          ]]))
('diff_gps: ', matrix([[ 2.2335959876e-05],
        [-1.9129099115e-05],
        [ 0.0000000000e+00]]))


In [25]:
#驗證 xy -> gps for point 3
compute_xy2gps(3)

('input xy: ', matrix([[1.066e+03],
        [3.760e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[ 23.9035358429],
        [121.5358810425],
        [  1.          ]]))
('diff_gps: ', matrix([[-4.6185277824e-14],
        [-1.9895196601e-13],
        [ 0.0000000000e+00]]))


In [26]:
#驗證 xy -> gps for point 4
compute_xy2gps(4)

('input xy: ', matrix([[148.],
        [396.],
        [  1.]]))
('output_gps: ', matrix([[ 23.90325737 ],
        [121.536277771],
        [  1.         ]]))
('diff_gps: ', matrix([[-1.2079226508e-13],
        [-4.2632564146e-14],
        [ 0.0000000000e+00]]))


In [27]:
#驗證 xy -> gps for point 5
compute_xy2gps(5)

('input xy: ', matrix([[910.],
        [958.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9038207315],
        [121.5364851426],
        [  1.          ]]))
('diff_gps: ', matrix([[4.8377406522e-05],
        [2.4266102997e-05],
        [0.0000000000e+00]]))


In [28]:
#驗證 xy -> gps for point 6
compute_xy2gps(6)

('input xy: ', matrix([[678.],
        [454.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9035682678],
        [121.536239624 ],
        [  1.          ]]))
('diff_gps: ', matrix([[-5.6843418861e-14],
        [-4.2632564146e-14],
        [ 0.0000000000e+00]]))


In [29]:
#驗證 xy -> gps for point 7
compute_xy2gps(7)

('input xy: ', matrix([[417.],
        [540.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9036154804],
        [121.5363917477],
        [  1.          ]]))
('diff_gps: ', matrix([[1.0972916183e-05],
        [1.4794603189e-05],
        [0.0000000000e+00]]))


In [30]:
#驗證 xy -> gps for point 8
compute_xy2gps(8)

('input xy: ', matrix([[615.],
        [456.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9035552113],
        [121.5362582048],
        [  1.          ]]))
('diff_gps: ', matrix([[-3.5198156532e-06],
        [-4.3074152813e-06],
        [ 0.0000000000e+00]]))


In [31]:
#驗證 xy -> gps for point 9
compute_xy2gps(9)

('input xy: ', matrix([[1.077e+03],
        [4.750e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[ 23.9036917801],
        [121.536184724 ],
        [  1.          ]]))
('diff_gps: ', matrix([[ 2.0515444124e-05],
        [-9.1236110507e-06],
        [ 0.0000000000e+00]]))


In [32]:
#驗證 xy -> gps for point 10
compute_xy2gps(10)

('input xy: ', matrix([[1.554e+03],
        [5.030e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[ 23.9038141824],
        [121.536136028 ],
        [  1.          ]]))
('diff_gps: ', matrix([[ 2.0847425347e-05],
        [-1.9672722487e-05],
        [ 0.0000000000e+00]]))


In [33]:
#驗證 xy -> gps for point 11
compute_xy2gps(11)

('input xy: ', matrix([[1.036e+03],
        [8.090e+02],
        [1.000e+00]]))
('output_gps: ', matrix([[ 23.9038114654],
        [121.5364398032],
        [  1.          ]]))
('diff_gps: ', matrix([[4.4833342635e-05],
        [1.7073674329e-05],
        [0.0000000000e+00]]))


In [34]:
#驗證 xy -> gps for point 12
compute_xy2gps(12)

('input xy: ', matrix([[ 55.],
        [448.],
        [  1.]]))
('output_gps: ', matrix([[ 23.9033927917],
        [121.5363845825],
        [  1.          ]]))
('diff_gps: ', matrix([[-1.0658141036e-13],
        [-2.8421709430e-14],
        [ 0.0000000000e+00]]))
